title: mecaproject
description: Manycore Operating System related researches

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

url: 'https://meca-project.github.io/' # your main domain
baseurl: '/overview' # if you're using custom domain keep this blank example: baseurl: ''

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec


permalink: 